### ISSUE TITLE
seek help

### ISSUE THREAD

**Issue by 807502278** [cozy-comfyui/cozy_ex_dynamic#1]
Nodes with dynamically added inputs cannot use the API mode.

**Comment by Amorano** [comment]
I assume it is because when exporting as an API workflow and re-importing the links to the dynamic inputs are disconnected.

Given the UI nature of the inputs it may just be a caveat that things that certain elements that mess with the UI of nodes are not good friends for API workflows.

Hopefully we can make the interface a more robust example.

**Comment by 807502278** [comment]
i see,thank you
Is this problem currently unsolvable?

**Comment by Amorano** [comment]
> i see,thank you Is this problem currently unsolvable?

unsolvable, probablly not, just maybe outside the scope of this since its only an example about the mechanism itself, not making the ultimate node for dynamic inputs =D

There are a lot of core changes being iterated in the UI part of ComfyUI at the moment. The team has been posting tweaks for a couple weeks now.

I am sure the actual problem itself will resolve soon enough.
